spring.application.name=HotelMS
spring.datasource.url=jdbc:postgresql://localhost:5432/amlan
spring.datasource.username=postgres
spring.datasource.password=hzkk4567@A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true